// Package queue_kafka implements a durable, Apache Kafka-backed job queue with
// support for delayed execution, per-type worker pools, automatic retry via
// dedicated retry topics, and a dead-letter queue (DLQ) for exhausted jobs.
//
// The queue package depends only on the KafkaStreamer interface, so it is not
// coupled to any specific Kafka client implementation. The *kafka.Client
// provided by github.com/thanhbvha/go-common/kafka satisfies this interface
// out of the box.
//
// Basic usage:
//
//	kc := kafka.MustConnect(ctx, kafka.DefaultConfig())
//	kafka.SetDefault(kc)
//
//	cfg := queue_kafka.DefaultConfig()
//	q := queue_kafka.New(kc, cfg)
//
//	q.RegisterJobType("email", queue_kafka.JobTypeOptions{Concurrency: 4, MaxRetry: 5})
//	q.RegisterHandler("email", func(job queue_kafka.Job) error { /* … */ return nil })
//
//	q.Start(ctx)
//	defer q.Stop()
//
//	q.Enqueue(ctx, "email", payload)
package queue_kafka

import (
	"context"
	"time"

	"github.com/thanhbvha/go-common/kafka"
)

// Logger is the logging interface consumed by Queue.
// It is intentionally identical to the kafka.Logger interface so that the
// same adapter can satisfy both without import cycles.
type Logger interface {
	Info(msg string, args ...any)
	Warn(msg string, args ...any)
	Error(msg string, args ...any)
	InfoAsync(msg string, args ...any)
	ErrorAsync(msg string, args ...any)
	WarnAsync(msg string, args ...any)
}

// KafkaStreamer defines the minimal Kafka API required by Queue.
// *kafka.Client from github.com/thanhbvha/go-common/kafka satisfies this
// interface, as does any compatible mock for testing.
type KafkaStreamer interface {
	// ProduceJSON marshals value to JSON and produces it to topic using key.
	ProduceJSON(ctx context.Context, topic string, key string, value any, headers ...kafka.Header) (kafka.ProduceResult, error)

	// Produce sends a pre-built Message to Kafka.
	Produce(ctx context.Context, msg kafka.Message) (kafka.ProduceResult, error)

	// Subscribe begins consuming from topics and invokes handler for each record.
	Subscribe(ctx context.Context, topics []string, handler kafka.RecordHandler) error

	// EnsureTopic creates a topic if it does not already exist.
	EnsureTopic(ctx context.Context, topic string, partitions int32, replicationFactor int16, configs map[string]string) error
}

// Config holds all tuneable parameters for a Queue instance backed by Kafka.
// Use DefaultConfig for a pre-filled value and override only what you need.
type Config struct {
	// TopicPrefix is prepended to all topic names auto-generated by this queue.
	// Default: "queue".
	TopicPrefix string

	// DefaultGroup is the consumer group ID when a job type has no custom group.
	// Default: "workers".
	DefaultGroup string

	// DefaultPartitions is the number of partitions used when auto-creating topics.
	// Increase for higher parallelism across consumer instances.
	// Default: 4.
	DefaultPartitions int32

	// DefaultReplicationFactor is the replication factor for auto-created topics.
	// Set to at least 3 for production clusters to tolerate broker failures.
	// Default: 1.
	DefaultReplicationFactor int16

	// DefaultRetentionMs is the message retention period in milliseconds applied
	// to auto-created topics. Default: 15 days (1_296_000_000 ms).
	DefaultRetentionMs int64

	// DefaultMaxRetry is the number of processing attempts before a job is moved
	// to the dead-letter queue. Default: 3.
	DefaultMaxRetry int

	// DefaultWorkerCount is the fallback number of consumer goroutines used when
	// no job types are explicitly registered. Default: 5.
	DefaultWorkerCount int

	// --- Delayed job settings ---

	// DelayedTopic is the Kafka topic that receives delayed jobs.
	// The delayed-job dispatcher goroutine reads from this topic and re-enqueues
	// jobs once their RunAt timestamp has been reached.
	// Default: "queue.delayed".
	DelayedTopic string

	// DelayCheckInterval controls how often the delayed-job dispatcher wakes up
	// to check for jobs whose RunAt has elapsed.
	// Default: 2s.
	DelayCheckInterval time.Duration

	// --- Dead-letter queue settings ---

	// DLQTopic is the Kafka topic that receives exhausted jobs (jobs that have
	// exceeded DefaultMaxRetry attempts without success).
	// Default: "queue.dlq".
	DLQTopic string

	// DLQRetentionMs is the message retention period for the DLQ topic in
	// milliseconds. Default: 30 days (2_592_000_000 ms).
	DLQRetentionMs int64

	// --- Worker settings ---

	// ProcessTimeout is the maximum time allowed to process a single job.
	// If a handler takes longer, the context passed to it is cancelled.
	// Default: 5 minutes.
	ProcessTimeout time.Duration

	// ShutdownTimeout is the maximum time to wait for in-flight jobs to
	// complete during graceful shutdown.
	// Default: 10s.
	ShutdownTimeout time.Duration

	// Logger receives operational log events. Set to nil to suppress logging.
	Logger Logger
}

// DefaultConfig returns a Config pre-populated with production-ready defaults.
func DefaultConfig() Config {
	return Config{
		TopicPrefix:              "queue",
		DefaultGroup:             "workers",
		DefaultPartitions:        64,
		DefaultReplicationFactor: 1,
		DefaultRetentionMs:       15 * 24 * 60 * 60 * 1000, // 15 days
		DefaultMaxRetry:          3,
		DefaultWorkerCount:       5,

		DelayedTopic:       "queue.delayed",
		DelayCheckInterval: 2 * time.Second,

		DLQTopic:       "queue.dlq",
		DLQRetentionMs: 30 * 24 * 60 * 60 * 1000, // 30 days

		ProcessTimeout:  5 * time.Minute,
		ShutdownTimeout: 10 * time.Second,
	}
}

// JobTypeOptions configures a specific job type registered with Queue.RegisterJobType.
type JobTypeOptions struct {
	// Concurrency is the number of parallel consumer goroutines for this job type.
	// Each goroutine is a member of the same consumer group, so partitions are
	// distributed evenly. Default: 1.
	Concurrency int

	// MaxRetry overrides Config.DefaultMaxRetry for this job type.
	// 0 means use the queue default.
	MaxRetry int

	// RetentionMs overrides the Kafka topic retention for this job type's topic.
	// 0 means use Config.DefaultRetentionMs.
	RetentionMs int64

	// BatchSize is the maximum number of Kafka records fetched per poll.
	// Default: 1.
	BatchSize int

	// Topic overrides the auto-generated Kafka topic name for this job type.
	// Empty = auto-generated as "<TopicPrefix>.<jobType>".
	Topic string

	// RetryTopic overrides the auto-generated retry topic name.
	// Empty = auto-generated as "<TopicPrefix>.<jobType>.retry".
	RetryTopic string

	// Group overrides the consumer group name for this job type.
	// Empty = auto-generated as "<DefaultGroup>.<jobType>".
	Group string

	// PartitionKey is a static key used to route all jobs of this type to the
	// same partition. Leave empty to use the job ID (round-robin effect).
	PartitionKey string
}

// jobTypeConfig is the resolved, internal representation of a registered type.
type jobTypeConfig struct {
	Concurrency  int
	MaxRetry     int
	RetentionMs  int64
	BatchSize    int
	Topic        string
	RetryTopic   string
	Group        string
	PartitionKey string
}
