package pubsub

import (
	"context"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	gonats "github.com/nats-io/nats.go"
	"github.com/thanhbvha/go-common/logger"
	"github.com/thanhbvha/go-common/nats"
)

// NATSPubSubManager manages subscriptions and publication of messages across multiple instances in a cluster using NATS.
type NATSPubSubManager struct {
	natsClient  *nats.Client
	nodeID      string
	subscribers map[string]*gonats.Subscription
	handlers    map[string]func(*CrossNodeMessage)
	mu          sync.RWMutex
	ctx         context.Context
	cancel      context.CancelFunc
}

var (
	globalNATSPubSub *NATSPubSubManager
	natsPubsubOnce   sync.Once
)

// GetGlobalNATSPubSub returns the default singleton NATSPubSubManager initialized with the default NATS client.
func GetGlobalNATSPubSub() *NATSPubSubManager {
	natsPubsubOnce.Do(func() {
		globalNATSPubSub = NewNATSPubSubManager()
	})
	return globalNATSPubSub
}

// NewNATSPubSubManager instantiates a new NATSPubSubManager. If the default NATS client is not set,
// it gracefully falls back to standalone loopback mode to support zero-config standalone runs.
func NewNATSPubSubManager() *NATSPubSubManager {
	ctx, cancel := context.WithCancel(context.Background())

	var client *nats.Client
	func() {
		defer func() {
			_ = recover() // Catch panic if nats.Default is not set
		}()
		client = nats.Default()
	}()

	if client == nil {
		logger.WarnAsync("NATS default client not set. WebSocket PubSub will run in standalone loopback mode.")
	}

	return &NATSPubSubManager{
		natsClient:  client,
		nodeID:      generateNodeID(),
		subscribers: make(map[string]*gonats.Subscription),
		handlers:    make(map[string]func(*CrossNodeMessage)),
		ctx:         ctx,
		cancel:      cancel,
	}
}

// NewNATSPubSubManagerWithClient instantiates a new NATSPubSubManager with a custom, user-provided NATS client.
func NewNATSPubSubManagerWithClient(client *nats.Client) *NATSPubSubManager {
	ctx, cancel := context.WithCancel(context.Background())

	return &NATSPubSubManager{
		natsClient:  client,
		nodeID:      generateNodeID(),
		subscribers: make(map[string]*gonats.Subscription),
		handlers:    make(map[string]func(*CrossNodeMessage)),
		ctx:         ctx,
		cancel:      cancel,
	}
}

// RegisterHandler binds a callback handler to a specific cross-node message type.
func (psm *NATSPubSubManager) RegisterHandler(messageType string, handler func(*CrossNodeMessage)) {
	psm.mu.Lock()
	defer psm.mu.Unlock()
	psm.handlers[messageType] = handler
}

// Subscribe listens to the specified NATS channels (subjects) and processes incoming messages.
func (psm *NATSPubSubManager) Subscribe(channels ...string) error {
	if psm.natsClient == nil || !psm.natsClient.IsConnected() {
		return nil // No-op in standalone/test mode
	}

	psm.mu.Lock()
	defer psm.mu.Unlock()

	nc := psm.natsClient.Native()
	if nc == nil {
		return fmt.Errorf("nats client is not connected")
	}

	for _, channel := range channels {
		if _, exists := psm.subscribers[channel]; exists {
			continue // Already subscribed
		}

		// In NATS, we supply a callback for the subscription.
		// We capture the channel variable to ensure correct closures.
		subChan := channel
		sub, err := nc.Subscribe(subChan, func(msg *gonats.Msg) {
			psm.processMessage(subChan, msg.Data)
		})
		if err != nil {
			return fmt.Errorf("failed to subscribe to channel: %s, err: %v", channel, err)
		}

		psm.subscribers[channel] = sub
	}

	logger.InfoAsync("Subscribed to NATS channels", "node_id", psm.nodeID, "channels", channels)
	return nil
}

// Unsubscribe stops listening to and closes the specified channels.
func (psm *NATSPubSubManager) Unsubscribe(channels ...string) error {
	if psm.natsClient == nil {
		return nil // No-op in standalone/test mode
	}

	psm.mu.Lock()
	defer psm.mu.Unlock()

	for _, channel := range channels {
		sub, exists := psm.subscribers[channel]
		if !exists {
			continue
		}

		if err := sub.Unsubscribe(); err != nil {
			logger.ErrorAsync("Failed to unsubscribe from NATS channel", "channel", channel, "error", err)
			return err
		}

		delete(psm.subscribers, channel)
	}

	logger.InfoAsync("Unsubscribed from NATS channels", "node_id", psm.nodeID, "channels", channels)
	return nil
}

// processMessage decodes and directs a single payload to its corresponding handler.
func (psm *NATSPubSubManager) processMessage(channel string, payload []byte) {
	var message CrossNodeMessage
	if err := json.Unmarshal(payload, &message); err != nil {
		logger.ErrorAsync("Failed to unmarshal cross-node message", "error", err, "payload", string(payload))
		return
	}

	// Skip messages generated by this node
	if message.NodeID == psm.nodeID {
		return
	}

	psm.mu.RLock()
	handler, exists := psm.handlers[message.Type]
	psm.mu.RUnlock()

	if !exists {
		logger.WarnAsync("No handler for message type", "type", message.Type, "channel", channel)
		return
	}

	go func() {
		defer func() {
			if r := recover(); r != nil {
				logger.ErrorAsync("Panic in message handler", "error", r, "type", message.Type, "node_id", psm.nodeID)
			}
		}()

		handler(&message)
	}()
}

// Publish transmits a CrossNodeMessage to the specified NATS channel (subject).
func (psm *NATSPubSubManager) Publish(channel string, message *CrossNodeMessage) error {
	message.NodeID = psm.nodeID
	message.Timestamp = time.Now()

	if psm.natsClient == nil || !psm.natsClient.IsConnected() {
		// Standalone/in-memory loopback mode
		psm.mu.RLock()
		handler, exists := psm.handlers[message.Type]
		psm.mu.RUnlock()
		if exists {
			go func() {
				defer func() {
					if r := recover(); r != nil {
						logger.ErrorAsync("Panic in loopback handler", "error", r)
					}
				}()
				handler(message)
			}()
		}
		return nil
	}

	data, err := json.Marshal(message)
	if err != nil {
		return fmt.Errorf("failed to marshal message: %w", err)
	}

	nc := psm.natsClient.Native()
	if nc == nil {
		return fmt.Errorf("nats client is not connected")
	}

	return nc.Publish(channel, data)
}

// BroadcastMessage sends a broadcast event to all subscribers of a specific shard ID.
func (psm *NATSPubSubManager) BroadcastMessage(shardID string, data map[string]interface{}) error {
	message := &CrossNodeMessage{
		Type:    MessageTypeBroadcast,
		ShardID: shardID,
		Data:    data,
	}

	channel := fmt.Sprintf("shard:%s", shardID)
	return psm.Publish(channel, message)
}

// BroadcastUserNotification sends a notification event to a specific user across different nodes.
func (psm *NATSPubSubManager) BroadcastUserNotification(shardID, userID string, data map[string]interface{}) error {
	message := &CrossNodeMessage{
		Type:    MessageTypeNotification,
		ShardID: shardID,
		UserID:  userID,
		Data:    data,
	}

	channel := fmt.Sprintf("shard:%s", shardID)
	return psm.Publish(channel, message)
}

// BroadcastRoomMessage distributes a chat room message to all room members across nodes.
func (psm *NATSPubSubManager) BroadcastRoomMessage(shardID, roomID string, data map[string]interface{}) error {
	message := &CrossNodeMessage{
		Type:    MessageTypeChatRoom,
		ShardID: shardID,
		RoomID:  roomID,
		Data:    data,
	}

	channel := fmt.Sprintf("shard:%s", shardID)
	return psm.Publish(channel, message)
}

// BroadcastChatMessage sends a direct chat message to a user on any cluster node.
func (psm *NATSPubSubManager) BroadcastChatMessage(shardID string, userID string, data map[string]interface{}) error {
	message := &CrossNodeMessage{
		Type:    MessageTypeChat,
		ShardID: shardID,
		UserID:  userID,
		Data:    data,
	}

	channel := fmt.Sprintf("shard:%s", shardID)
	return psm.Publish(channel, message)
}

// NotifyUserJoin sends a join event to other nodes when a user connects.
func (psm *NATSPubSubManager) NotifyUserJoin(shardID, userID, clientIP string) error {
	message := &CrossNodeMessage{
		Type:    MessageTypeUserJoin,
		ShardID: shardID,
		UserID:  userID,
		Data: map[string]interface{}{
			"client_ip": clientIP,
		},
	}

	channel := fmt.Sprintf("shard:%s", shardID)
	return psm.Publish(channel, message)
}

// NotifyUserLeave sends a leave event to other nodes when a user disconnects.
func (psm *NATSPubSubManager) NotifyUserLeave(shardID, userID string) error {
	message := &CrossNodeMessage{
		Type:    MessageTypeUserLeave,
		ShardID: shardID,
		UserID:  userID,
	}

	channel := fmt.Sprintf("shard:%s", shardID)
	return psm.Publish(channel, message)
}

// NotifyShardCreate broadcasts a shard creation notice globally to system subscribers.
func (psm *NATSPubSubManager) NotifyShardCreate(shardID string) error {
	message := &CrossNodeMessage{
		Type:    MessageTypeShardCreate,
		ShardID: shardID,
	}

	return psm.Publish("system", message)
}

// NotifyShardDestroy broadcasts a shard destruction notice globally.
func (psm *NATSPubSubManager) NotifyShardDestroy(shardID string) error {
	message := &CrossNodeMessage{
		Type:    MessageTypeShardDestroy,
		ShardID: shardID,
	}

	return psm.Publish("system", message)
}

// SendNodeStatus publishes node status metrics to the system control topic.
func (psm *NATSPubSubManager) SendNodeStatus(data map[string]interface{}) error {
	message := &CrossNodeMessage{
		Type: MessageTypeNodeStatus,
		Data: data,
	}

	return psm.Publish("system", message)
}

// GetNodeID returns the unique identifier of the current cluster node.
func (psm *NATSPubSubManager) GetNodeID() string {
	return psm.nodeID
}

// GetStats returns metrics and current status of the pub/sub connection.
func (psm *NATSPubSubManager) GetStats() map[string]interface{} {
	psm.mu.RLock()
	defer psm.mu.RUnlock()

	channels := make([]string, 0, len(psm.subscribers))
	for channel := range psm.subscribers {
		channels = append(channels, channel)
	}

	handlers := make([]string, 0, len(psm.handlers))
	for msgType := range psm.handlers {
		handlers = append(handlers, msgType)
	}

	return map[string]interface{}{
		"node_id":             psm.nodeID,
		"subscribed_channels": len(psm.subscribers),
		"channels":            channels,
		"registered_handlers": len(psm.handlers),
		"handlers":            handlers,
		"mode":                "nats",
	}
}

// Shutdown gracefully unsubscribes from all channels and releases the connections.
func (psm *NATSPubSubManager) Shutdown() error {
	logger.InfoAsync("Shutting down NATS pub/sub manager", "node_id", psm.nodeID)

	psm.cancel()

	psm.mu.Lock()
	defer psm.mu.Unlock()

	for channel, sub := range psm.subscribers {
		if err := sub.Unsubscribe(); err != nil {
			logger.ErrorAsync("Error closing NATS subscription", "channel", channel, "error", err)
		}
	}

	psm.subscribers = make(map[string]*gonats.Subscription)
	psm.handlers = make(map[string]func(*CrossNodeMessage))

	logger.InfoAsync("NATS pub/sub manager shutdown complete", "node_id", psm.nodeID)
	return nil
}
