package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/thanhbvha/go-common/examples/graphql_web/graph/model"
	"github.com/thanhbvha/go-common/examples/graphql_web/service"
	common_graphql "github.com/thanhbvha/go-common/graphql"
)

// Author is the resolver for the author field.
func (r *postResolver) Author(ctx context.Context, obj *model.Post) (*model.User, error) {
	// Use DataLoader to fetch users instead of querying the DB directly (Solves N+1 issue)
	loader := ctx.Value("userLoader").(*common_graphql.DataLoader[int, *model.User])
	return loader.Load(ctx, obj.AuthorID)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	return service.GetUsers(), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	return service.GetPosts(), nil
}

// Posts is the resolver for the posts field on User.
func (r *userResolver) Posts(ctx context.Context, obj *model.User) ([]*model.Post, error) {
	return service.GetPostsByAuthor(obj.ID), nil
}

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type (
	postResolver  struct{ *Resolver }
	queryResolver struct{ *Resolver }
	userResolver  struct{ *Resolver }
)
